export interface OrchestrationPromptEntry {
  symbol: string;
  scene: string;
  role: string;
  buildDefaultContent: () => string;
}

const DEFAULT_PLANNER_TASK_DECOMPOSITION_PROMPT = [
  '将用户需求拆解为可执行任务清单并返回 JSON。',
  '需求: {{prompt}}',
  '输出规则:',
  '1) JSON 结构: {"mode":"sequential|parallel|hybrid","tasks":[{"title":"","description":"","priority":"low|medium|high|urgent","dependencies":[0]}]}',
  '2) dependencies 为当前任务依赖的前置任务索引数组。',
  '3) mode 优先使用 {{mode}}。',
  '3.1) {{requirementScope}}',
  '4) 若需求涉及编排/分配/通知，最后一个任务应为"汇总输出编排结果 JSON"。',
  '5) task 的 description 必须具体可执行，包含文件路径、接口名、字段名等具体信息（如有）。禁止空泛描述。',
].join('\n');

const DEFAULT_PLANNER_GENERATING_PROMPT = [
  '【当前阶段声明 — 最高优先级】',
  '你当前处于 generating 阶段，只负责提交下一步任务。',
  '- 允许调用 `builtin.sys-mg.mcp.orchestration.submit-task` 和 `builtin.sys-mg.internal.tool-meta.get-tool-schema`。',
  '- 如果不确定 submit-task 的参数格式，先调用 get-tool-schema 查询。',
  '- 禁止调用 requirement.* 工具，禁止输出确认性文本。',
  '- 每次只提交一个任务。',
  '- submit-task 的 planId 必须是: {{planId}}',
  '',
  '{{currentStepGuidanceSection}}',
  '## 计划上下文',
  '- 当前步骤: {{nextStep}} / {{totalSteps}}',
  '- requirementId: {{requirementId}}',
  '- Plan 目标: {{planGoal}}',
  '{{completedTasksSummary}}',
  '',
  '{{fallbackRulesSection}}',
  '## 当前编排进度',
  '已创建任务数: {{createdTaskCount}}',
  '',
  '{{completedTasksBlock}}',
  '{{failedTasksBlock}}',
  '{{lastErrorBlock}}',
  '{{remainingStepsSection}}',
  '{{recommendedAgentSection}}',
  '## 输出规则',
  '1) isGoalReached 判断：仅当大纲中所有步骤均已提交任务后才允许 isGoalReached=true。当前仍有未完成步骤时，禁止设置 isGoalReached=true。',
  '2) 调用 submit-task 时必须传真实 agentId。{{recommendedAgentHint}}',
  '3) 禁止直接输出文本 JSON，结果必须通过工具调用给出。',
].join('\n');

const DEFAULT_PLANNER_INITIALIZE_PROMPT = [
  '## 你正在执行 phaseInitialize 阶段',
  '',
  '### 执行顺序（严格遵守）',
  '本阶段分为 Phase 1 和 Phase 2，**必须按顺序执行**：',
  '1. 先完成 Phase 1 的全部工具调用（写入 outline）',
  '2. Phase 1 完成后，再执行 Phase 2 的工具调用（写入 taskContext）',
  '3. 每个工具只调用一次，禁止重复调用同一工具',
  '',
  '### Phase 1：大纲与 Prompt 预编译（必做）',
  '',
  '**步骤**：',
  '1. 调用 `builtin.sys-mg.internal.agent-master.list-agents` 获取可用 agent 列表（含 capabilitySet）。',
  '2. 根据 domainType、sourcePrompt 和已注入 skill 的步骤定义，确定执行步骤大纲。',
  '3. 为每个步骤生成 4 个阶段的 phasePrompts，并选择推荐执行 agent。',
  '4. 调用 `builtin.sys-mg.mcp.orchestration.plan-initialize` 写入 outline（planId={{planId}}，mode="outline"）。',
  '',
  '**OutlineItem 数据结构**（data 数组中每个元素必须符合）：',
  '```',
  '{',
  '  "step": number,          // 步骤序号，从 1 开始',
  '  "title": string,          // 步骤标题',
  '  "taskType": string,       // 合法值: general | research | development.plan | development.exec | development.review',
  '  "recommendedAgent": {     // 推荐执行 agent（根据 capabilitySet 匹配 taskType）',
  '    "agentId": string,',
  '    "agentName": string,',
  '    "reason": string',
  '  },',
  '  "phasePrompts": {         // 各阶段预编译 prompt（generating 必填）',
  '    "generating": string,   // planner 生成 task 时的指令',
  '    "execute": string,      // executor 执行任务时的详细指导',
  '    "post_execute": string  // planner 执行后评估的决策规则（必填）',
  '  },',
  '  "preExecuteActions": [    // 执行前需要调用的工具列表（可选，无则系统自动跳过 pre_execute 阶段）',
  '    {',
  '      "tool": string,       // 工具 ID（如 builtin.sys-mg.mcp.requirement.update-status）',
  '      "params": {           // 工具参数（参数值中可引用 taskContext 字段，系统会在运行时替换）',
  '        "requirementId": "从 taskContext.requirementId 获取",',
  '        "status": "目标状态值"',
  '      }',
  '    }',
  '  ]',
  '}',
  '```',
  '',
  '### Phase 2：扩展步骤（Phase 1 完成后执行）',
  '',
  '检查已激活的 skill 中是否定义了 `## phaseInitialize 扩展步骤`。',
  '- 如果有：按 skill 中定义的工具调用序列执行，调用结果通过 plan-initialize(mode=taskContext) 写入。',
  '- 如果没有：Phase 2 跳过，直接结束 phaseInitialize 阶段。',
  '',
  '{{extensionStepHint}}',
  '',
  '### 约束',
  '- **执行顺序**：Phase 1（outline）必须先于 Phase 2（taskContext）完成。',
  '- 禁止调用 `builtin.sys-mg.mcp.orchestration.submit-task`。',
  '- 如果不确定工具参数格式，可调用 `builtin.sys-mg.internal.tool-meta.get-tool-schema`。',
  '- 所有初始化产出必须通过 `plan-initialize` 工具写入 metadata。',
  '- 禁止输出确认性文本。优先使用工具调用。',
  '- 每个工具只调用一次，禁止重复调用。',
  '',
  '### 输入',
  '- planId: {{planId}}',
  '- domainType: {{domainType}}',
  '- sourcePrompt: {{sourcePrompt}}',
  '{{existingRequirementHint}}',
].join('\n');

const DEFAULT_PLANNER_DEFAULT_OUTLINE_PROMPT = JSON.stringify(
  {
    development: [
      {
        step: 1,
        title: '制定技术开发计划',
        taskType: 'development.plan',
        phasePrompts: {
          generating: '生成技术规划任务，要求输出结构化开发计划与验收要点。',
          post_execute: '验证开发计划是否完整；完整则 generate_next，否则 redesign/retry。',
        },
      },
      {
        step: 2,
        title: '执行开发',
        taskType: 'development.exec',
        phasePrompts: {
          generating: '生成开发执行任务，要求按上一步计划落地代码变更并附验证证据。',
          post_execute: '验证是否完成代码变更与必要验证；通过则 generate_next。',
        },
      },
      {
        step: 3,
        title: '实现评估',
        taskType: 'development.review',
        phasePrompts: {
          generating: '生成实现评审任务，要求输出评审结论与修复建议。',
          post_execute: '验证评审结论是否完整，完成则 stop。',
        },
      },
    ],
    research: [
      {
        step: 1,
        title: '执行任务',
        taskType: 'research',
        phasePrompts: {
          generating: '生成可执行任务，明确输入、动作、产出与验收标准。',
          post_execute: '根据执行结果判断 generate_next 或 stop。',
        },
      },
    ],
    general: [
      {
        step: 1,
        title: '执行任务',
        taskType: 'general',
        phasePrompts: {
          generating: '生成可执行任务，明确输入、动作、产出与验收标准。',
          post_execute: '根据执行结果判断 generate_next 或 stop。',
        },
      },
    ],
  },
  null,
  2,
);

const DEFAULT_PRE_EXECUTE_CONTEXT_PROMPT = [
  '【当前阶段声明 — 最高优先级】',
  '你当前处于 **pre_execute** 阶段，不是 phaseInitialize 阶段，也不是 generate 阶段。',
  '- **本阶段禁止调用 submit-task。**',
  '- 可调用 get-tool-schema 查询参数格式。',
  '- 你只需执行下方列出的工具调用，然后返回评估 JSON。',
  '',
  '[pre_execute 阶段] step {{step}} — {{taskTitle}}',
  '',
  '{{taskContextSection}}',
  '你需要执行 {{preActionsCount}} 个预定义工具调用，然后返回评估 JSON。',
  '',
  '**请直接使用以下参数 tool_call**',
  'requirementId 需要用替换为taskContext中requirementId(req-* 格式!!!,不要截断)，不要用其他 ID 或 placeholder',
  '{{preActionsSection}}',
  '工具调用完成后，返回：',
  '{"allowExecute":true,"riskFlags":[],"notes":""}',
  '',
  '约束：',
  '- 第一条回复只能是 <tool_call>，前面不要有任何文字',
  '- 只调用上面列出的工具',
].join('\n');

const DEFAULT_POST_EXECUTE_CONTEXT_PROMPT = [
  '【当前阶段声明 — 最高优先级】',
  '你当前处于 **post_execute** 阶段（执行后决策阶段），不是 phaseInitialize 阶段，也不是 generate 阶段。',
  '- **本阶段禁止调用 submit-task 和 requirement.* 工具。**',
  '- 可调用 get-tool-schema 查询 report-task-run-result 参数格式。',
  '- 你只需分析执行结果，返回决策 JSON。',
  '',
  '请进行执行后决策，返回 JSON。',
  '',
  '## 任务信息',
  'step: {{step}}',
  'taskId: {{taskId}}',
  'taskTitle: {{taskTitle}}',
  'runtimeTaskType: {{runtimeTaskType}}',
  'executionStatus: {{executionStatus}}',
  '',
  '## 执行结果',
  '{{executionOutputSection}}',
  '{{executionErrorSection}}',
  '',
  '{{progressSection}}',
  '## 决策规则（严格遵守）',
  '{{decisionRulesSection}}',
  '',
  '返回格式: {"action":"generate_next|stop|redesign|retry","reason":"..."}',
  'action=redesign 时必须附带 redesignTaskId。',
].join('\n');

const DEFAULT_RESEARCH_OUTPUT_CONTRACT_PROMPT = [
  'Research output contract (MUST follow one format):',
  'Preferred JSON format:',
  '{"findings":[{"rank":1,"title":"...","summary":"...","source":"https://..."}]}',
  'Execution proof (REQUIRED):',
  'RESEARCH_EXECUTION_PROOF: {"toolCalls":["websearch","webfetch"],"fetchedUrls":["https://...","https://..."]}',
  'Requirements:',
  '- at least 3 findings',
  '- each finding includes title/summary/source',
  '- source should be URL',
].join('\n');

export const ORCHESTRATION_PROMPTS: Record<string, OrchestrationPromptEntry> = {
  plannerTaskDecomposition: {
    symbol: 'PLANNER_TASK_DECOMPOSITION_PROMPT',
    scene: 'orchestration',
    role: 'planner-task-decomposition',
    buildDefaultContent: () => DEFAULT_PLANNER_TASK_DECOMPOSITION_PROMPT,
  },
  plannerGenerating: {
    symbol: 'PLANNER_GENERATING_PROMPT',
    scene: 'orchestration',
    role: 'planner-generating',
    buildDefaultContent: () => DEFAULT_PLANNER_GENERATING_PROMPT,
  },
  plannerInitialize: {
    symbol: 'PLANNER_INITIALIZE_PROMPT',
    scene: 'orchestration',
    role: 'planner-initialize',
    buildDefaultContent: () => DEFAULT_PLANNER_INITIALIZE_PROMPT,
  },
  plannerDefaultOutline: {
    symbol: 'PLANNER_DEFAULT_OUTLINE_PROMPT',
    scene: 'orchestration',
    role: 'planner-default-outline',
    buildDefaultContent: () => DEFAULT_PLANNER_DEFAULT_OUTLINE_PROMPT,
  },
  preExecuteContext: {
    symbol: 'PRE_EXECUTE_CONTEXT_PROMPT',
    scene: 'orchestration',
    role: 'pre-execute-context',
    buildDefaultContent: () => DEFAULT_PRE_EXECUTE_CONTEXT_PROMPT,
  },
  postExecuteContext: {
    symbol: 'POST_EXECUTE_CONTEXT_PROMPT',
    scene: 'orchestration',
    role: 'post-execute-context',
    buildDefaultContent: () => DEFAULT_POST_EXECUTE_CONTEXT_PROMPT,
  },
  researchOutputContract: {
    symbol: 'RESEARCH_OUTPUT_CONTRACT_PROMPT',
    scene: 'orchestration',
    role: 'research-output-contract',
    buildDefaultContent: () => DEFAULT_RESEARCH_OUTPUT_CONTRACT_PROMPT,
  },
};
