import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { Agent, AgentDocument } from '../../shared/schemas/agent.schema';
import { AgentClientService } from '../agents-client/agent-client.service';
import { Task } from '../../shared/types';

interface PlannerTaskDraft {
  title: string;
  description: string;
  priority: 'low' | 'medium' | 'high' | 'urgent';
  dependencies: number[];
}

interface PlannerResult {
  mode: 'sequential' | 'parallel' | 'hybrid';
  tasks: PlannerTaskDraft[];
  plannerAgentId?: string;
  strategyNote?: string;
}

@Injectable()
export class PlannerService {
  constructor(
    @InjectModel(Agent.name) private readonly agentModel: Model<AgentDocument>,
    private readonly agentClientService: AgentClientService,
  ) {}

  async planFromPrompt(input: {
    prompt: string;
    mode?: 'sequential' | 'parallel' | 'hybrid';
    plannerAgentId?: string;
  }): Promise<PlannerResult> {
    const mode = input.mode || 'hybrid';
    if (input.plannerAgentId) {
      const result = await this.planByAgent(input.prompt, input.plannerAgentId, mode);
      if (result) {
        return result;
      }
    }

    const defaultPlanner = await this.agentModel.findOne({ isActive: true }).sort({ createdAt: 1 }).exec();
    if (defaultPlanner?._id) {
      const result = await this.planByAgent(input.prompt, defaultPlanner._id.toString(), mode);
      if (result) {
        return result;
      }
    }

    return this.planByHeuristic(input.prompt, mode);
  }

  private async planByAgent(
    prompt: string,
    plannerAgentId: string,
    mode: 'sequential' | 'parallel' | 'hybrid',
  ): Promise<PlannerResult | null> {
    const task: Task = {
      title: 'Planner agent task decomposition',
      description: [
        '将用户需求拆解为可执行任务清单并返回 JSON。',
        `需求: ${prompt}`,
        '输出规则:',
        '1) 仅输出 JSON，不要附加解释。',
        '2) JSON 结构: {"mode":"sequential|parallel|hybrid","tasks":[{"title":"","description":"","priority":"low|medium|high|urgent","dependencies":[0]}]}',
        '3) tasks 数量 3-8 条。',
        '4) dependencies 为当前任务依赖的前置任务索引数组。',
        `5) mode 优先使用 ${mode}。`,
        '6) 若存在发送邮件/外部动作任务，优先依赖“邮件草稿/内容生成”任务，而不是“校对/润色”任务，避免过度阻塞。',
      ].join('\n'),
      type: 'planning',
      priority: 'high',
      status: 'pending',
      assignedAgents: [plannerAgentId],
      teamId: 'orchestration',
      messages: [],
    };

    try {
      const response = await this.agentClientService.executeTask(plannerAgentId, task, {
        teamContext: {
          mode: 'planning',
          format: 'json',
        },
      });
      const parsed = this.tryParseJson(response);
      if (!parsed?.tasks || !Array.isArray(parsed.tasks) || parsed.tasks.length === 0) {
        return null;
      }

      const tasks: PlannerTaskDraft[] = parsed.tasks.slice(0, 8).map((item: any, index: number) => ({
        title: String(item.title || `子任务 ${index + 1}`).slice(0, 120),
        description: String(item.description || item.title || '').slice(0, 1000),
        priority: this.normalizePriority(item.priority),
        dependencies: Array.isArray(item.dependencies)
          ? item.dependencies.filter((dep: any) => Number.isInteger(dep) && dep >= 0)
          : index > 0
            ? [index - 1]
            : [],
      }));

      return {
        mode: this.normalizeMode(parsed.mode, mode),
        tasks: this.optimizeDependencies(tasks),
        plannerAgentId,
        strategyNote: 'Generated by planner agent',
      };
    } catch {
      return null;
    }
  }

  private planByHeuristic(prompt: string, mode: 'sequential' | 'parallel' | 'hybrid'): PlannerResult {
    const blocks = prompt
      .split(/[\n。！？!?;；]+/)
      .map((item) => item.trim())
      .filter(Boolean);

    const taskDrafts = (blocks.length > 1 ? blocks : this.defaultBreakdown(prompt)).slice(0, 8);
    const tasks: PlannerTaskDraft[] = taskDrafts.map((item, index) => ({
      title: `步骤 ${index + 1}: ${item.slice(0, 30)}`,
      description: item,
      priority: index === 0 ? 'high' : 'medium',
      dependencies: index === 0 ? [] : [index - 1],
    }));

    return {
      mode,
      tasks: this.optimizeDependencies(tasks),
      strategyNote: 'Generated by heuristic planner fallback',
    };
  }

  private defaultBreakdown(prompt: string): string[] {
    return [
      `分析需求与边界: ${prompt}`,
      '设计实现方案并明确任务依赖关系',
      '实现核心功能并补充必要接口',
      '验证结果并整理交付说明',
    ];
  }

  private tryParseJson(content: string): any | null {
    const trimmed = (content || '').trim();
    if (!trimmed) {
      return null;
    }

    try {
      return JSON.parse(trimmed);
    } catch {
      const fenced = trimmed.match(/```json\s*([\s\S]*?)```/i)?.[1] || trimmed.match(/```\s*([\s\S]*?)```/i)?.[1];
      if (fenced) {
        try {
          return JSON.parse(fenced.trim());
        } catch {
          return null;
        }
      }

      const start = trimmed.indexOf('{');
      const end = trimmed.lastIndexOf('}');
      if (start >= 0 && end > start) {
        try {
          return JSON.parse(trimmed.slice(start, end + 1));
        } catch {
          return null;
        }
      }
      return null;
    }
  }

  private normalizePriority(input: string): 'low' | 'medium' | 'high' | 'urgent' {
    if (input === 'low' || input === 'medium' || input === 'high' || input === 'urgent') {
      return input;
    }
    return 'medium';
  }

  private normalizeMode(input: string, fallback: 'sequential' | 'parallel' | 'hybrid'): 'sequential' | 'parallel' | 'hybrid' {
    if (input === 'sequential' || input === 'parallel' || input === 'hybrid') {
      return input;
    }
    return fallback;
  }

  private optimizeDependencies(tasks: PlannerTaskDraft[]): PlannerTaskDraft[] {
    if (!tasks.length) {
      return tasks;
    }

    const draftIndex = tasks.findIndex((task) => {
      const text = `${task.title} ${task.description}`.toLowerCase();
      return text.includes('draft email') || text.includes('email draft') || text.includes('邮件草稿') || text.includes('撰写邮件');
    });

    const reviewIndex = tasks.findIndex((task) => {
      const text = `${task.title} ${task.description}`.toLowerCase();
      return text.includes('review') || text.includes('finalize') || text.includes('校对') || text.includes('润色');
    });

    const sendIndex = tasks.findIndex((task) => {
      const text = `${task.title} ${task.description}`.toLowerCase();
      return text.includes('send email') || text.includes('发送邮件') || text.includes('发邮件');
    });

    if (sendIndex >= 0 && draftIndex >= 0) {
      tasks[sendIndex].dependencies = [draftIndex];
    }

    if (reviewIndex >= 0 && draftIndex >= 0) {
      tasks[reviewIndex].dependencies = Array.from(new Set([...tasks[reviewIndex].dependencies, draftIndex]));
    }

    return tasks;
  }
}
