import {
  AGENT_CREATE_TOOL_ID,
  AGENT_LIST_TOOL_ID,
  LEGACY_AGENT_LIST_TOOL_ID,
  RD_DOCS_WRITE_TOOL_ID,
} from './builtin-tool-definitions';

export const BUILTIN_TOOLS = [
      {
        id: 'builtin.web-retrieval.internal.web-search.exa',
        name: 'Web Search Exa',
        description: 'Search web information via Exa (auto + highlights compact)',
        type: 'web_search' as const,
        category: 'Information Retrieval',
        requiredPermissions: [{ id: 'basic_web', name: 'Basic Web Access', level: 'basic' }],
        tokenCost: 10,
        implementation: {
          type: 'built_in' as const,
          parameters: { query: 'string', maxResults: 'number' },
        },
      },
      {
        id: 'composio.web-retrieval.mcp.web-search.serp',
        name: 'Web Search SERP',
        description: 'Search web information via Composio SERPAPI',
        type: 'web_search' as const,
        category: 'Information Retrieval',
        requiredPermissions: [{ id: 'basic_web', name: 'Basic Web Access', level: 'basic' }],
        tokenCost: 10,
        implementation: {
          type: 'built_in' as const,
          parameters: { query: 'string', maxResults: 'number' },
        },
      },
      {
        id: 'builtin.web-retrieval.internal.web-fetch.fetch',
        name: 'Web Fetch',
        description: 'Fetch webpage content by URL and return clean text',
        type: 'web_search' as const,
        category: 'Information Retrieval',
        requiredPermissions: [{ id: 'basic_web', name: 'Basic Web Access', level: 'basic' }],
        tokenCost: 8,
        implementation: {
          type: 'built_in' as const,
          parameters: { url: 'string', maxChars: 'number', timeoutMs: 'number' },
        },
      },
      {
        id: 'builtin.data-analysis.internal.content-analysis.extract',
        name: 'Content Extract',
        description: 'Extract clean text, key bullets and numeric rows from raw html or text',
        type: 'data_analysis' as const,
        category: 'Information Retrieval',
        requiredPermissions: [{ id: 'basic_web', name: 'Basic Web Access', level: 'basic' }],
        tokenCost: 6,
        implementation: {
          type: 'built_in' as const,
          parameters: { content: 'string', maxBullets: 'number', maxNumericRows: 'number' },
        },
      },
      {
        id: 'composio.communication.mcp.slack.send-message',
        name: 'Slack',
        description: 'Send Slack messages via Composio',
        type: 'api_call' as const,
        category: 'Communication',
        requiredPermissions: [{ id: 'slack_send', name: 'Slack Message Permission', level: 'intermediate' }],
        tokenCost: 15,
        implementation: {
          type: 'built_in' as const,
          parameters: { channel: 'string', text: 'string' },
        },
      },
      {
        id: 'composio.communication.mcp.gmail.send-email',
        name: 'Gmail',
        description: 'Send or draft email via Composio',
        type: 'api_call' as const,
        category: 'Communication',
        requiredPermissions: [{ id: 'gmail_send', name: 'Gmail Permission', level: 'intermediate' }],
        tokenCost: 20,
        implementation: {
          type: 'built_in' as const,
          parameters: { to: 'string', subject: 'string', body: 'string', action: 'string' },
        },
      },
      {
        id: 'builtin.sys-mg.mcp.inner-message.send-internal-message',
        name: 'Send Internal Message',
        description: 'Send direct internal message to another agent',
        prompt:
          '当你需要通知其他 Agent 时，调用 builtin.sys-mg.mcp.inner-message.send-internal-message。默认使用短版开工通知（任务一句话+截止点），仅当用户明确要求时再补充验收细节。只有拿到返回中的 messageId，才可以对用户确认“已发送”。',
        type: 'api_call' as const,
        category: 'Communication',
        requiredPermissions: [{ id: 'inner_message_write', name: 'Inner Message Write', level: 'basic' }],
        tokenCost: 3,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            receiverAgentId: 'string',
            title: 'string',
            content: 'string',
            eventType: 'string',
            payload: 'object',
            dedupKey: 'string',
            maxAttempts: 'number',
          },
        },
      },
      {
        id: 'builtin.sys-mg.internal.rd-related.repo-read',
        name: 'Repo Read',
        description: 'Execute read-only bash commands to read local repository files (git log, cat, ls, grep)',
        prompt:
          '你拥有 builtin.sys-mg.internal.rd-related.repo-read 工具，可执行只读 bash 命令（如 git log、cat、ls、grep 等）来读取本地仓库文件。当你需要了解代码或文档内容时，请优先使用 builtin.sys-mg.internal.rd-related.repo-read 直接读取。',
        type: 'data_analysis' as const,
        category: 'Engineering Intelligence',
        requiredPermissions: [{ id: 'repo_read', name: 'Repository Read', level: 'basic' }],
        tokenCost: 2,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            command: 'string',
          },
        },
      },
      {
        id: 'builtin.sys-mg.internal.rd-related.docs-read',
        name: 'Code Docs Reader',
        description: 'Read raw documentation files from docs/ directory',
        prompt:
          '当用户询问"当前系统实现了哪些核心功能/系统能力清单/docs里实现了什么"时，优先级如下：1) 优先使用 builtin.sys-mg.internal.rd-related.repo-read 执行 "git log"、"ls docs/"、"cat docs/..."、"grep ..." 等命令自行读取；2) 其次调用 builtin.sys-mg.internal.rd-related.docs-read 读取文档。若 builtin.sys-mg.internal.rd-related.docs-read 返回 0 命中或 fallback 信号，必须自动重试（放宽 focus 或不传 focus），仍失败再切换 builtin.sys-mg.internal.rd-related.repo-read 直接列目录并读取文档；不要向用户发起二选一确认。必须基于实际读取的内容回答，不得臆测。',
        type: 'data_analysis' as const,
        category: 'Engineering Intelligence',
        requiredPermissions: [{ id: 'repo_docs_read', name: 'Repository Docs Read', level: 'basic' }],
        tokenCost: 3,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            focus: 'string',
            maxFiles: 'number',
          },
        },
      },
      {
        id: RD_DOCS_WRITE_TOOL_ID,
        name: 'Code Docs Writer',
        description: 'Write markdown docs into docs/ directory with strict path and extension guard',
        prompt:
          '当你需要新增或更新研发文档时，调用 builtin.sys-mg.internal.rd-related.docs-write；仅写 docs/** 下的 .md 文件，优先使用 create/update/append 明确意图，避免覆盖不相关内容。',
        type: 'data_analysis' as const,
        category: 'Engineering Intelligence',
        requiredPermissions: [{ id: 'repo_docs_write', name: 'Repository Docs Write', level: 'admin' }],
        tokenCost: 4,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            filePath: 'string',
            content: 'string',
            mode: 'string',
            overwrite: 'boolean',
          },
        },
      },
      {
        id: 'builtin.sys-mg.internal.rd-related.updates-read',
        name: 'Code Updates Reader',
        description: 'Read raw git commit history from repository',
        prompt:
          '当用户询问"最近24小时/最近一天系统主要更新"时，优先级如下：1) 优先使用 builtin.sys-mg.internal.rd-related.repo-read 执行 "git log --since=..." 等命令自行读取提交记录；2) 其次调用 builtin.sys-mg.internal.rd-related.updates-read。必须基于实际提交内容回答，不得臆测。',
        type: 'data_analysis' as const,
        category: 'Engineering Intelligence',
        requiredPermissions: [{ id: 'repo_git_read', name: 'Repository Git Read', level: 'basic' }],
        tokenCost: 3,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            hours: 'number',
            limit: 'number',
          },
        },
      },
      {
        id: 'builtin.sys-mg.mcp.rd-intelligence.engineering-statistics-run',
        name: 'Engineering Statistics Run',
        description: 'Trigger engineering statistics snapshot and return summary',
        type: 'data_analysis' as const,
        category: 'Engineering Intelligence',
        requiredPermissions: [{ id: 'rd_statistics_run', name: 'RD Statistics Run', level: 'basic' }],
        tokenCost: 3,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            receiverId: 'string',
            scope: 'string',
            tokenMode: 'string',
            projectIds: 'string[]',
            triggeredBy: 'string',
          },
        },
      },
      {
        id: AGENT_LIST_TOOL_ID,
        name: 'Agents MCP List',
        description: 'List current agents, roles, and capability summaries from MCP visibility rules',
        prompt:
          '当用户询问“系统里有哪些agents/当前有哪些agent/agent列表”时，请优先调用 builtin.sys-mg.internal.agent-master.list-agents 工具获取实时名单，再基于工具结果回答。',
        type: 'data_analysis' as const,
        category: 'System Intelligence',
        requiredPermissions: [{ id: 'agent_registry_read', name: 'Agent Registry Read', level: 'basic' }],
        tokenCost: 3,
        implementation: {
          type: 'built_in' as const,
          parameters: { includeHidden: 'boolean', limit: 'number' },
        },
      },
      {
        id: AGENT_CREATE_TOOL_ID,
        name: 'Agents MCP Create Agent',
        description: 'Create a new agent via MCP with provider default api-key fallback',
        type: 'data_analysis' as const,
        category: 'System Intelligence',
        requiredPermissions: [{ id: 'agent_registry_write', name: 'Agent Registry Write', level: 'admin' }],
        tokenCost: 6,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            name: 'string',
            roleId: 'string',
            description: 'string',
            systemPrompt: 'string',
            model: 'object',
            modelId: 'string',
            provider: 'string',
            apiKeyId: 'string',
            capabilities: 'string[]',
            tools: 'string[]',
            permissions: 'string[]',
            learningAbility: 'number',
            isActive: 'boolean',
          },
        },
      },
      {
        id: 'builtin.sys-mg.mcp.model-admin.list-models',
        name: 'Model MCP List Models',
        description: 'List models currently available in system registry',
        prompt:
          '当用户询问“系统里有哪些模型/当前有哪些模型/模型列表”时，请优先调用 builtin.sys-mg.mcp.model-admin.list-models 获取实时模型清单，再回答。',
        type: 'data_analysis' as const,
        category: 'Model Management',
        requiredPermissions: [{ id: 'model_registry_read', name: 'Model Registry Read', level: 'basic' }],
        tokenCost: 3,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            provider: 'string',
            limit: 'number',
          },
        },
      },
      {
        id: 'builtin.sys-mg.mcp.model-admin.add-model',
        name: 'Model MCP Add Model',
        description: 'Add a model into system model registry with deduplication',
        type: 'data_analysis' as const,
        category: 'Model Management',
        requiredPermissions: [{ id: 'model_registry_write', name: 'Model Registry Write', level: 'admin' }],
        tokenCost: 5,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            provider: 'string',
            model: 'string',
            name: 'string',
            id: 'string',
            maxTokens: 'number',
            temperature: 'number',
            topP: 'number',
          },
        },
      },
      {
        id: 'builtin.sys-mg.internal.memory.search-memo',
        name: 'Memo MCP Search',
        description: 'Search agent memo memory with progressive loading summaries',
        prompt: '在处理任务时，优先调用 builtin.sys-mg.internal.memory.search-memo 检索相关历史备忘录。',
        type: 'data_analysis' as const,
        category: 'Memory',
        requiredPermissions: [{ id: 'memo_read', name: 'Agent Memo Read', level: 'basic' }],
        tokenCost: 2,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            query: 'string',
            category: 'string',
            memoType: 'string',
            limit: 'number',
            detail: 'boolean',
          },
        },
      },
      {
        id: 'builtin.sys-mg.internal.memory.append-memo',
        name: 'Memo MCP Append',
        description: 'Append or create memo entries for long-term memory',
        prompt:
          '当形成关键结论或后续动作时，调用 builtin.sys-mg.internal.memory.append-memo 追加到目标Agent备忘录。必须显式传 targetAgentId（或 agentId）写入目标对象；topic 必须 memoType=knowledge；achievement/criticism 必须 memoType=standard 且按追加模式写入，已有内容前先插入分割线“—”再追加新记录，禁止覆盖历史。',
        type: 'data_analysis' as const,
        category: 'Memory',
        requiredPermissions: [{ id: 'memo_write', name: 'Agent Memo Write', level: 'basic' }],
        tokenCost: 3,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            title: 'string',
            content: 'string',
            category: 'string',
            memoType: 'string',
            memoKind: 'string',
            targetAgentId: 'string',
            memoId: 'string',
            taskId: 'string',
            topic: 'string',
            tags: 'string[]',
          },
        },
      },
      {
        id: 'builtin.sys-mg.mcp.skill-master.list-skills',
        name: 'Skill MCP List Skills',
        description: 'List system skills with optional title fuzzy search',
        type: 'data_analysis' as const,
        category: 'Skill',
        requiredPermissions: [{ id: 'skill_read', name: 'Skill Read', level: 'basic' }],
        tokenCost: 2,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            title: 'string',
            status: 'string',
            category: 'string',
            includeMetadata: 'boolean',
            limit: 'number',
            page: 'number',
          },
        },
      },
      {
        id: 'builtin.sys-mg.mcp.skill-master.create-skill',
        name: 'Skill MCP Create Skill',
        description: 'Create a new skill in system skill library',
        type: 'api_call' as const,
        category: 'Skill',
        requiredPermissions: [{ id: 'skill_write', name: 'Skill Write', level: 'intermediate' }],
        tokenCost: 4,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            title: 'string',
            name: 'string',
            description: 'string',
            category: 'string',
            tags: 'string[]',
            sourceType: 'string',
            sourceUrl: 'string',
            provider: 'string',
            version: 'string',
            status: 'string',
            confidenceScore: 'number',
            metadata: 'object',
            content: 'string',
            contentType: 'string',
          },
        },
      },
      {
        id: 'builtin.sys-mg.mcp.audit.list-human-operation-log',
        name: 'Human Operation Log MCP List',
        description: 'List operation logs for the human bound to the requesting exclusive assistant',
        type: 'data_analysis' as const,
        category: 'Audit',
        requiredPermissions: [{ id: 'human_operation_log_read', name: 'Human Operation Log Read', level: 'basic' }],
        tokenCost: 4,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            from: 'string',
            to: 'string',
            action: 'string',
            resourceKeyword: 'string',
            success: 'boolean',
            statusCode: 'number',
            page: 'number',
            pageSize: 'number',
          },
        },
      },
      {
        id: 'builtin.sys-mg.mcp.orchestration.create-plan',
        name: 'Orchestration Create Plan',
        description: 'Create orchestration plan from prompt in meeting workflow',
        type: 'api_call' as const,
        category: 'Orchestration',
        requiredPermissions: [{ id: 'orchestration_write', name: 'Orchestration Write', level: 'intermediate' }],
        tokenCost: 6,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            prompt: 'string',
            title: 'string',
            mode: 'string',
            plannerAgentId: 'string',
            autoRun: 'boolean',
            requirementId: 'string',
          },
        },
      },
      {
        id: 'builtin.sys-mg.mcp.orchestration.update-plan',
        name: 'Orchestration Update Plan',
        description: 'Update orchestration plan in meeting workflow',
        type: 'api_call' as const,
        category: 'Orchestration',
        requiredPermissions: [{ id: 'orchestration_write', name: 'Orchestration Write', level: 'intermediate' }],
        tokenCost: 4,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            planId: 'string',
            title: 'string',
            prompt: 'string',
            mode: 'string',
            plannerAgentId: 'string',
            metadata: 'object',
          },
        },
      },
      {
        id: 'builtin.sys-mg.mcp.orchestration.run-plan',
        name: 'Orchestration Run Plan',
        description: 'Run an orchestration plan in meeting workflow',
        type: 'api_call' as const,
        category: 'Orchestration',
        requiredPermissions: [{ id: 'orchestration_write', name: 'Orchestration Write', level: 'intermediate' }],
        tokenCost: 4,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            planId: 'string',
            continueOnFailure: 'boolean',
            confirm: 'boolean',
          },
        },
      },
      {
        id: 'builtin.sys-mg.mcp.orchestration.get-plan',
        name: 'Orchestration Get Plan',
        description: 'Get orchestration plan details',
        type: 'api_call' as const,
        category: 'Orchestration',
        requiredPermissions: [{ id: 'orchestration_read', name: 'Orchestration Read', level: 'basic' }],
        tokenCost: 3,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            planId: 'string',
          },
        },
      },
      {
        id: 'builtin.sys-mg.mcp.orchestration.list-plans',
        name: 'Orchestration List Plans',
        description: 'List orchestration plans',
        type: 'api_call' as const,
        category: 'Orchestration',
        requiredPermissions: [{ id: 'orchestration_read', name: 'Orchestration Read', level: 'basic' }],
        tokenCost: 2,
        implementation: {
          type: 'built_in' as const,
          parameters: {},
        },
      },
      {
        id: 'builtin.sys-mg.mcp.orchestration.reassign-task',
        name: 'Orchestration Reassign Task',
        description: 'Reassign orchestration task executor',
        type: 'api_call' as const,
        category: 'Orchestration',
        requiredPermissions: [{ id: 'orchestration_write', name: 'Orchestration Write', level: 'intermediate' }],
        tokenCost: 4,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            taskId: 'string',
            executorType: 'string',
            executorId: 'string',
            reason: 'string',
            confirm: 'boolean',
          },
        },
      },
      {
        id: 'builtin.sys-mg.mcp.orchestration.complete-human-task',
        name: 'Orchestration Complete Human Task',
        description: 'Mark waiting human task as completed',
        type: 'api_call' as const,
        category: 'Orchestration',
        requiredPermissions: [{ id: 'orchestration_write', name: 'Orchestration Write', level: 'intermediate' }],
        tokenCost: 4,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            taskId: 'string',
            summary: 'string',
            output: 'string',
            confirm: 'boolean',
          },
        },
      },
      {
        id: 'builtin.sys-mg.mcp.orchestration.create-schedule',
        name: 'Orchestration Create Schedule',
        description: 'Create orchestration scheduler plan in meeting workflow',
        type: 'api_call' as const,
        category: 'Orchestration',
        requiredPermissions: [{ id: 'orchestration_write', name: 'Orchestration Write', level: 'intermediate' }],
        tokenCost: 6,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            planId: 'string',
            scheduleType: 'string',
            expression: 'string',
            intervalMs: 'number',
            timezone: 'string',
            enabled: 'boolean',
          },
        },
      },
      {
        id: 'builtin.sys-mg.mcp.orchestration.update-schedule',
        name: 'Orchestration Update Schedule',
        description: 'Update orchestration scheduler plan in meeting workflow',
        type: 'api_call' as const,
        category: 'Orchestration',
        requiredPermissions: [{ id: 'orchestration_write', name: 'Orchestration Write', level: 'intermediate' }],
        tokenCost: 5,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            scheduleId: 'string',
            scheduleType: 'string',
            expression: 'string',
            intervalMs: 'number',
            timezone: 'string',
            enabled: 'boolean',
          },
        },
      },
      {
        id: 'builtin.sys-mg.mcp.orchestration.debug-task',
        name: 'Orchestration Debug Task',
        description: 'Debug-run a single orchestration task with optional draft edits',
        type: 'api_call' as const,
        category: 'Orchestration',
        requiredPermissions: [{ id: 'orchestration_write', name: 'Orchestration Write', level: 'intermediate' }],
        tokenCost: 5,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            taskId: 'string',
            title: 'string',
            description: 'string',
            resetResult: 'boolean',
          },
        },
      },
      {
        id: 'builtin.sys-mg.mcp.requirement.list',
        name: 'Requirement List',
        description: 'List EI requirements with filters',
        type: 'api_call' as const,
        category: 'Engineering Intelligence',
        requiredPermissions: [{ id: 'requirement_read', name: 'Requirement Read', level: 'basic' }],
        tokenCost: 3,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            status: 'string',
            assigneeAgentId: 'string',
            localProjectId: 'string',
            search: 'string',
            limit: 'number',
          },
        },
      },
      {
        id: 'builtin.sys-mg.mcp.requirement.get',
        name: 'Requirement Get',
        description: 'Get EI requirement details',
        type: 'api_call' as const,
        category: 'Engineering Intelligence',
        requiredPermissions: [{ id: 'requirement_read', name: 'Requirement Read', level: 'basic' }],
        tokenCost: 2,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            requirementId: 'string',
          },
        },
      },
      {
        id: 'builtin.sys-mg.mcp.requirement.create',
        name: 'Requirement Create',
        description: 'Create EI requirement',
        type: 'api_call' as const,
        category: 'Engineering Intelligence',
        requiredPermissions: [{ id: 'requirement_write', name: 'Requirement Write', level: 'intermediate' }],
        tokenCost: 5,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            title: 'string',
            description: 'string',
            priority: 'string',
            labels: 'string[]',
            createdById: 'string',
            createdByName: 'string',
            createdByType: 'string',
            localProjectId: 'string',
          },
        },
      },
      {
        id: 'builtin.sys-mg.mcp.requirement.update-status',
        name: 'Requirement Update Status',
        description: 'Update EI requirement status',
        prompt:
          '会议分配场景请先更新 requirement 状态（建议 assigned 或 in_progress）再发送通知；若用户已明确同意执行，不要再二次确认文案。',
        type: 'api_call' as const,
        category: 'Engineering Intelligence',
        requiredPermissions: [{ id: 'requirement_write', name: 'Requirement Write', level: 'intermediate' }],
        tokenCost: 3,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            requirementId: 'string',
            status: 'string',
            changedById: 'string',
            changedByName: 'string',
            changedByType: 'string',
            note: 'string',
          },
        },
      },
      {
        id: 'builtin.sys-mg.mcp.requirement.assign',
        name: 'Requirement Assign',
        description: 'Assign EI requirement to agent',
        prompt:
          '会议分配场景执行 requirement.assign 后，必须补充结构化三段式回执：动作1（已分配：requirementId/执行人/状态）+ 动作2（已通知：消息摘要）+ 下一步（检查时间点）。用户明确同意后直接执行，不重复确认语气。',
        type: 'api_call' as const,
        category: 'Engineering Intelligence',
        requiredPermissions: [{ id: 'requirement_write', name: 'Requirement Write', level: 'intermediate' }],
        tokenCost: 3,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            requirementId: 'string',
            toAgentId: 'string',
            toAgentName: 'string',
            assignedById: 'string',
            assignedByName: 'string',
            reason: 'string',
          },
        },
      },
      {
        id: 'builtin.sys-mg.mcp.requirement.comment',
        name: 'Requirement Comment',
        description: 'Append EI requirement comment',
        type: 'api_call' as const,
        category: 'Engineering Intelligence',
        requiredPermissions: [{ id: 'requirement_write', name: 'Requirement Write', level: 'basic' }],
        tokenCost: 2,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            requirementId: 'string',
            content: 'string',
            authorId: 'string',
            authorName: 'string',
            authorType: 'string',
          },
        },
      },
      {
        id: 'builtin.sys-mg.mcp.requirement.sync-github',
        name: 'Requirement Sync Github',
        description: 'Sync EI requirement to GitHub issue',
        type: 'api_call' as const,
        category: 'Engineering Intelligence',
        requiredPermissions: [{ id: 'requirement_write', name: 'Requirement Write', level: 'intermediate' }],
        tokenCost: 4,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            requirementId: 'string',
            owner: 'string',
            repo: 'string',
            labels: 'string[]',
          },
        },
      },
      {
        id: 'builtin.sys-mg.mcp.requirement.board',
        name: 'Requirement Board',
        description: 'Get EI requirement board view',
        type: 'api_call' as const,
        category: 'Engineering Intelligence',
        requiredPermissions: [{ id: 'requirement_read', name: 'Requirement Read', level: 'basic' }],
        tokenCost: 2,
        implementation: {
          type: 'built_in' as const,
          parameters: {},
        },
      },
      {
        id: 'builtin.sys-mg.mcp.meeting.list-meetings',
        name: 'Meeting MCP List',
        description: 'List current meetings',
        type: 'data_analysis' as const,
        category: 'Meeting',
        requiredPermissions: [{ id: 'meeting_read', name: 'Meeting Read', level: 'basic' }],
        tokenCost: 2,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            status: 'string',
            limit: 'number',
          },
        },
      },
      {
        id: 'builtin.sys-mg.mcp.meeting.send-message',
        name: 'Meeting MCP Send Message',
        description: 'Send a message to a specific meeting',
        type: 'api_call' as const,
        category: 'Meeting',
        requiredPermissions: [{ id: 'meeting_write', name: 'Meeting Write', level: 'basic' }],
        tokenCost: 3,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            meetingId: 'string',
            content: 'string',
            type: 'string',
          },
        },
      },
      {
        id: 'builtin.sys-mg.mcp.meeting.update-status',
        name: 'Meeting MCP Update Status',
        description: 'Update meeting status (start/end/pause/resume)',
        type: 'api_call' as const,
        category: 'Meeting',
        requiredPermissions: [{ id: 'meeting_write', name: 'Meeting Write', level: 'intermediate' }],
        tokenCost: 4,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            meetingId: 'string',
            action: 'string',
          },
        },
      },
      {
        id: 'builtin.sys-mg.mcp.meeting.generate-summary',
        name: 'Meeting MCP Generate Summary',
        description: 'Generate meeting summary for a specific meeting',
        type: 'api_call' as const,
        category: 'Meeting',
        requiredPermissions: [{ id: 'meeting_write', name: 'Meeting Write', level: 'intermediate' }],
        tokenCost: 5,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            meetingId: 'string',
            skipIfExists: 'boolean',
          },
        },
      },
    ];

export const IMPLEMENTED_TOOL_IDS = [
  ...BUILTIN_TOOLS.map((tool) => tool.id),
  LEGACY_AGENT_LIST_TOOL_ID,
];
