import {
  TOOL_ID__AGENT_CREATE,
  TOOL_ID__AGENT_LIST,
  TOOL_ID__AGENT_ROLE_CREATE,
  TOOL_ID__AGENT_ROLE_DELETE,
  TOOL_ID__AGENT_ROLE_LIST,
  TOOL_ID__AGENT_ROLE_UPDATE,
  TOOL_ID__EMPLYEE_LOGS,
  TOOL_ID__CONTENT_EXTRACT,
  TOOL_ID__ENGINEERING_COMMIT_READ,
  TOOL_ID__ENGINEERING_STATISTICS_DOCS_HEAT_RUN,
  TOOL_ID__ENGINEERING_DOCS_READ,
  TOOL_ID__ENGINEERING_REPO_READ,
  TOOL_ID__ENGINEERING_STATISTICS_FILES_RUN,
  TOOL_ID__GMAIL_SEND_EMAIL,
  TOOL_ID__GET_TOOL_SCHEMA,
  TOOL_ID__MEETING_GET_DETAIL,
  TOOL_ID__MEETING_LIST,
  TOOL_ID__MEETING_SAVE_SUMMARY,
  TOOL_ID__MEETING_SEND_MESSAGE,
  TOOL_ID__MEETING_UPDATE_STATUS,
  TOOL_ID__AGENT_MEMORY_APPEND_MEMO,
  TOOL_ID__AGENT_MEMORY_SEARCH_MEMO,
  TOOL_ID__AGENT_MODEL_ADD,
  TOOL_ID__AGENT_MODEL_LIST,
  TOOL_ID__ORCHESTRATION_CREATE_PLAN,
  TOOL_ID__ORCHESTRATION_GET_PLAN,
  TOOL_ID__ORCHESTRATION_LIST_PLANS,
  TOOL_ID__ORCHESTRATION_INIT_PLAN,
  TOOL_ID__ORCHESTRATION_RUN_PLAN,
  TOOL_ID__ORCHESTRATION_SUBMIT_TASK,
  TOOL_ID__ORCHESTRATION_SUBMIT_TASK_RUN_RESULT,
  TOOL_ID__ORCHESTRATION_UPDATE_PLAN,
  TOOL_ID__PROMPT_REGISTRY_GET_TEMPLATE,
  TOOL_ID__PROMPT_REGISTRY_LIST_TEMPLATES,
  TOOL_ID__PROMPT_REGISTRY_SAVE_TEMPLATE,
  TOOL_ID__ENGINEERING_DOCS_WRITE,
  TOOL_ID__ENGINEERING_REPO_WRITER,
  TOOL_ID__REQUIREMENT_CREATE,
  TOOL_ID__REQUIREMENT_GET,
  TOOL_ID__REQUIREMENT_LIST,
  TOOL_ID__REQUIREMENT_SYNC_GITHUB,
  TOOL_ID__REQUIREMENT_UPDATE,
  TOOL_ID__REQUIREMENT_UPDATE_STATUS,
  TOOL_ID__SEND_INTERNAL_MESSAGE,
  TOOL_ID__AGENT_SKILL_CREATE,
  TOOL_ID__AGENT_SKILL_LIST,
  TOOL_ID__SLACK_SEND_MESSAGE,
  TOOL_ID__WEB_FETCH,
  TOOL_ID__WEB_SEARCH_EXA,
  TOOL_ID__WEB_SEARCH_SERP,
} from './builtin-tool-definitions';

export const BUILTIN_TOOLS = [
      {
        id: TOOL_ID__WEB_SEARCH_EXA,
        name: 'Web Search Exa',
        description: 'Search web information via Exa (auto + highlights compact)',
        type: 'web_search' as const,
        category: 'Information Retrieval',
        requiredPermissions: [{ id: 'basic_web', name: 'Basic Web Access', level: 'basic' }],
        tokenCost: 10,
        implementation: {
          type: 'built_in' as const,
          parameters: { query: 'string', maxResults: 'number' },
        },
      },
      {
        id: TOOL_ID__WEB_SEARCH_SERP,
        name: 'Web Search SERP',
        description: 'Search web information via Composio SERPAPI',
        type: 'web_search' as const,
        category: 'Information Retrieval',
        requiredPermissions: [{ id: 'basic_web', name: 'Basic Web Access', level: 'basic' }],
        tokenCost: 10,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            type: 'object',
            required: ['query'],
            properties: {
              query: { type: 'string', description: '搜索关键词' },
              maxResults: { type: 'number', description: '最大结果数' },
            },
          },
        },
      },
      {
        id: TOOL_ID__WEB_FETCH,
        name: 'Web Fetch',
        description: 'Fetch webpage content by URL and return clean text',
        type: 'web_search' as const,
        category: 'Information Retrieval',
        requiredPermissions: [{ id: 'basic_web', name: 'Basic Web Access', level: 'basic' }],
        tokenCost: 8,
        implementation: {
          type: 'built_in' as const,
          parameters: { url: 'string', maxChars: 'number', timeoutMs: 'number' },
        },
      },
      {
        id: TOOL_ID__CONTENT_EXTRACT,
        name: 'Content Extract',
        description: 'Extract clean text, key bullets and numeric rows from raw html or text',
        type: 'data_analysis' as const,
        category: 'Information Retrieval',
        requiredPermissions: [{ id: 'basic_web', name: 'Basic Web Access', level: 'basic' }],
        tokenCost: 6,
        implementation: {
          type: 'built_in' as const,
          parameters: { content: 'string', maxBullets: 'number', maxNumericRows: 'number' },
        },
      },
      {
        id: TOOL_ID__SLACK_SEND_MESSAGE,
        name: 'Slack',
        description: 'Send Slack messages via Composio',
        type: 'api_call' as const,
        category: 'Communication',
        requiredPermissions: [{ id: 'slack_send', name: 'Slack Message Permission', level: 'intermediate' }],
        tokenCost: 15,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            type: 'object',
            required: ['channel', 'text'],
            properties: {
              channel: { type: 'string', description: 'Slack 频道名称或 ID' },
              text: { type: 'string', description: '消息内容' },
            },
          },
        },
      },
      {
        id: TOOL_ID__GMAIL_SEND_EMAIL,
        name: 'Gmail',
        description: 'Send or draft email via Composio',
        type: 'api_call' as const,
        category: 'Communication',
        requiredPermissions: [{ id: 'gmail_send', name: 'Gmail Permission', level: 'intermediate' }],
        tokenCost: 20,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            type: 'object',
            required: ['to', 'subject', 'body'],
            properties: {
              to: { type: 'string', description: '收件人邮箱' },
              subject: { type: 'string', description: '邮件主题' },
              body: { type: 'string', description: '邮件正文' },
              action: { type: 'string', enum: ['send', 'draft'], description: '发送或存为草稿' },
            },
          },
        },
      },
      {
        id: TOOL_ID__SEND_INTERNAL_MESSAGE,
        name: 'Send Internal Message',
        description: 'Send direct internal message to another agent',
        prompt: `当你需要通知其他 Agent 时，调用 ${TOOL_ID__SEND_INTERNAL_MESSAGE}。默认使用短版开工通知（任务一句话+截止点），仅当用户明确要求时再补充验收细节。只有拿到返回中的 messageId，才可以对用户确认“已发送”。`,
        type: 'api_call' as const,
        category: 'Communication',
        authFree: true,
        requiredPermissions: [{ id: 'inner_message_write', name: 'Inner Message Write', level: 'basic' }],
        tokenCost: 3,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            type: 'object',
            required: ['receiverAgentId', 'title', 'content'],
            additionalProperties: false,
            properties: {
              receiverAgentId: { type: 'string' },
              title: { type: 'string' },
              content: { type: 'string' },
              eventType: { type: 'string' },
              payload: { type: 'object' },
              dedupKey: { type: 'string' },
              maxAttempts: { type: 'number' },
            },
          },
        },
      },
      {
        id: TOOL_ID__GET_TOOL_SCHEMA,
        name: 'Get Tool Schema',
        description:
          '查询指定工具的参数契约（inputSchema），返回 required 字段、属性类型和枚举约束。在调用不熟悉的工具前，先用此工具查询参数格式。',
        prompt:
          '当你不确定某个工具的参数格式时，先调用 get-tool-schema 查询其 inputSchema，然后根据返回的参数契约正确构造 tool_call。不要猜测参数结构。',
        type: 'api_call' as const,
        category: 'System',
        authFree: true,
        requiredPermissions: [],
        tokenCost: 1,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            type: 'object',
            required: ['toolId'],
            properties: {
              toolId: {
                type: 'string',
                description: `要查询的工具 ID（如 ${TOOL_ID__ORCHESTRATION_SUBMIT_TASK}）`,
              },
            },
          },
        },
      },
      {
        id: TOOL_ID__ENGINEERING_REPO_READ,
        name: 'Repo Read',
        description: 'Execute read-only bash commands to read local repository files (git log, cat, ls, grep)',
        prompt: `你拥有 ${TOOL_ID__ENGINEERING_REPO_READ} 工具，可执行只读 bash 命令（如 git log、cat、ls、grep 等）来读取本地仓库文件。当你需要了解代码或文档内容时，请优先使用 ${TOOL_ID__ENGINEERING_REPO_READ} 直接读取。`,
        type: 'data_analysis' as const,
        category: 'Engineering Intelligence',
        requiredPermissions: [{ id: 'repo_read', name: 'Repository Read', level: 'basic' }],
        tokenCost: 2,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            command: 'string',
          },
        },
      },
      {
        id: TOOL_ID__ENGINEERING_REPO_WRITER,
        name: 'Repo Writer',
        description: 'Clone or refresh remote repository into data/repos sandbox directory',
        prompt: `当你需要导入外部仓库内容时，先调用 ${TOOL_ID__ENGINEERING_REPO_WRITER}，action 使用 git-clone，将仓库拉取到 data/repos/ 下，再用 repo-read 分析内容；若识别出可复用 Prompt，请继续调用 ${TOOL_ID__PROMPT_REGISTRY_SAVE_TEMPLATE} 落库。`,
        type: 'file_operation' as const,
        category: 'Engineering Intelligence',
        requiredPermissions: [{ id: 'repo_write', name: 'Repository Write', level: 'intermediate' }],
        tokenCost: 4,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            type: 'object',
            required: ['action', 'repoUrl'],
            additionalProperties: false,
            properties: {
              action: { type: 'string' },
              repoUrl: { type: 'string' },
              branch: { type: 'string' },
              targetDir: { type: 'string' },
            },
          },
        },
      },
      {
        id: TOOL_ID__ENGINEERING_DOCS_READ,
        name: 'Code Docs Reader',
        description: 'Read raw documentation files from docs/ directory',
        prompt: `当用户询问"当前系统实现了哪些核心功能/系统能力清单/docs里实现了什么"时，优先级如下：1) 优先使用 ${TOOL_ID__ENGINEERING_REPO_READ} 执行 "git log"、"ls docs/"、"cat docs/..."、"grep ..." 等命令自行读取；2) 其次调用 ${TOOL_ID__ENGINEERING_DOCS_READ} 读取文档。若 ${TOOL_ID__ENGINEERING_DOCS_READ} 返回 0 命中或 fallback 信号，必须自动重试（放宽 focus 或不传 focus），仍失败再切换 ${TOOL_ID__ENGINEERING_REPO_READ} 直接列目录并读取文档；不要向用户发起二选一确认。必须基于实际读取的内容回答，不得臆测。`,
        type: 'data_analysis' as const,
        category: 'Engineering Intelligence',
        requiredPermissions: [{ id: 'repo_docs_read', name: 'Repository Docs Read', level: 'basic' }],
        tokenCost: 3,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            focus: 'string',
            maxFiles: 'number',
          },
        },
      },
      {
        id: TOOL_ID__ENGINEERING_DOCS_WRITE,
        name: 'Code Docs Writer',
        description: 'Write markdown docs into docs/ directory with strict path and extension guard',
        prompt: `当你需要新增或更新研发文档时，调用 ${TOOL_ID__ENGINEERING_DOCS_WRITE}；仅写 docs/** 下的 .md 文件，优先使用 create/update/append 明确意图，避免覆盖不相关内容。`,
        type: 'data_analysis' as const,
        category: 'Engineering Intelligence',
        requiredPermissions: [{ id: 'repo_docs_write', name: 'Repository Docs Write', level: 'admin' }],
        tokenCost: 4,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            filePath: 'string',
            content: 'string',
            mode: 'string',
            overwrite: 'boolean',
          },
        },
      },
      {
        id: TOOL_ID__ENGINEERING_COMMIT_READ,
        name: 'Code Updates Reader',
        description: 'Read raw git commit history from repository',
        prompt: `当用户询问"最近24小时/最近一天系统主要更新"时，优先级如下：1) 优先使用 ${TOOL_ID__ENGINEERING_REPO_READ} 执行 "git log --since=..." 等命令自行读取提交记录；2) 其次调用 ${TOOL_ID__ENGINEERING_COMMIT_READ}。必须基于实际提交内容回答，不得臆测。`,
        type: 'data_analysis' as const,
        category: 'Engineering Intelligence',
        requiredPermissions: [{ id: 'repo_git_read', name: 'Repository Git Read', level: 'basic' }],
        tokenCost: 3,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            hours: 'number',
            limit: 'number',
          },
        },
      },
      {
        id: TOOL_ID__PROMPT_REGISTRY_SAVE_TEMPLATE,
        name: 'Prompt Registry Save Template',
        description: 'Create or version prompt templates in prompt registry with optional auto-publish',
        prompt: `当你已经整理好 Prompt 模板内容时，调用 ${TOOL_ID__PROMPT_REGISTRY_SAVE_TEMPLATE} 保存模板；单条模式必填 scene/role/content，批量模式使用 templates 数组，并在需要时设置 autoPublish=true。`,
        type: 'data_analysis' as const,
        category: 'System Intelligence',
        requiredPermissions: [{ id: 'prompt_write', name: 'Prompt Registry Write', level: 'intermediate' }],
        tokenCost: 4,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            type: 'object',
            oneOf: [
              {
                type: 'object',
                required: ['scene', 'role', 'content'],
              },
              {
                type: 'object',
                required: ['templates'],
              },
            ],
            additionalProperties: true,
            properties: {
              scene: { type: 'string' },
              role: { type: 'string' },
              content: { type: 'string' },
              description: { type: 'string' },
              category: { type: 'string' },
              tags: { type: 'array' },
              source: { type: 'object' },
              templates: { type: 'array' },
              autoPublish: { type: 'boolean' },
            },
          },
        },
      },
      {
        id: TOOL_ID__PROMPT_REGISTRY_LIST_TEMPLATES,
        name: 'Prompt Registry List Templates',
        description: 'List prompt templates by scene role category and status without returning content field',
        prompt: `当你需要浏览可用 Prompt 模板时，先调用 ${TOOL_ID__PROMPT_REGISTRY_LIST_TEMPLATES}；该工具仅返回摘要信息（不含 content），可先筛选 scene/role/category，再决定是否调用 get 查看全文。`,
        type: 'data_analysis' as const,
        category: 'System Intelligence',
        requiredPermissions: [{ id: 'prompt_read', name: 'Prompt Registry Read', level: 'basic' }],
        tokenCost: 2,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            type: 'object',
            additionalProperties: false,
            properties: {
              scene: { type: 'string' },
              role: { type: 'string' },
              category: { type: 'string' },
              status: { type: 'string' },
              limit: { type: 'number' },
            },
          },
        },
      },
      {
        id: TOOL_ID__PROMPT_REGISTRY_GET_TEMPLATE,
        name: 'Prompt Registry Get Template',
        description: 'Get a full prompt template by templateId or by scene and role',
        prompt: `当你已选定一个 Prompt 模板并需要完整内容时，调用 ${TOOL_ID__PROMPT_REGISTRY_GET_TEMPLATE}。优先使用 scene+role 获取当前生效版本；如已知 templateId，也可直接查询。`,
        type: 'data_analysis' as const,
        category: 'System Intelligence',
        requiredPermissions: [{ id: 'prompt_read', name: 'Prompt Registry Read', level: 'basic' }],
        tokenCost: 2,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            type: 'object',
            additionalProperties: false,
            properties: {
              scene: { type: 'string' },
              role: { type: 'string' },
              templateId: { type: 'string' },
            },
          },
        },
      },
      {
        id: TOOL_ID__ENGINEERING_STATISTICS_FILES_RUN,
        name: 'Engineering Statistics Run',
        description: 'Trigger engineering statistics snapshot and return summary',
        type: 'data_analysis' as const,
        category: 'Engineering Intelligence',
        requiredPermissions: [{ id: 'rd_statistics_run', name: 'RD Statistics Run', level: 'basic' }],
        tokenCost: 3,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            receiverId: 'string',
            scope: 'string',
            tokenMode: 'string',
            projectIds: 'string[]',
            triggeredBy: 'string',
          },
        },
      },
      {
        id: TOOL_ID__ENGINEERING_STATISTICS_DOCS_HEAT_RUN,
        name: 'Docs Heat Run',
        description: 'Trigger docs heat refresh and return summary',
        type: 'data_analysis' as const,
        category: 'Engineering Intelligence',
        requiredPermissions: [{ id: 'rd_statistics_run', name: 'RD Statistics Run', level: 'basic' }],
        tokenCost: 3,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            topN: 'number',
            triggeredBy: 'string',
          },
        },
      },
      {
        id: TOOL_ID__AGENT_LIST,
        name: 'Agents MCP List',
        description: 'List current agents with role/capability summaries and runtime status from Redis cache',
        prompt: `当用户询问“系统里有哪些agents/当前有哪些agent/agent列表”时，请优先调用 ${TOOL_ID__AGENT_LIST} 工具获取实时名单，再基于工具结果回答。`,
        type: 'data_analysis' as const,
        category: 'System Intelligence',
        requiredPermissions: [{ id: 'agent_registry_read', name: 'Agent Registry Read', level: 'basic' }],
        tokenCost: 3,
        implementation: {
          type: 'built_in' as const,
          parameters: { includeHidden: 'boolean', limit: 'number', agentId: 'string' },
        },
      },
      {
        id: TOOL_ID__AGENT_CREATE,
        name: 'Agents MCP Create Agent',
        description: 'Create a new agent via MCP with provider default api-key fallback',
        type: 'data_analysis' as const,
        category: 'System Intelligence',
        requiredPermissions: [{ id: 'agent_registry_write', name: 'Agent Registry Write', level: 'admin' }],
        tokenCost: 6,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            name: 'string',
            roleId: 'string',
            description: 'string',
            systemPrompt: 'string',
            model: 'object',
            modelId: 'string',
            provider: 'string',
            apiKeyId: 'string',
            capabilities: 'string[]',
            tools: 'string[]',
            permissions: 'string[]',
            learningAbility: 'number',
            isActive: 'boolean',
          },
        },
      },
      {
        id: TOOL_ID__AGENT_ROLE_LIST,
        name: 'Agent Role MCP List Roles',
        description: 'List agent roles with optional active/inactive status filter',
        type: 'data_analysis' as const,
        category: 'System Intelligence',
        requiredPermissions: [{ id: 'agent_role_registry_read', name: 'Agent Role Registry Read', level: 'basic' }],
        tokenCost: 3,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            status: 'string',
            includeInactive: 'boolean',
          },
        },
      },
      {
        id: TOOL_ID__AGENT_ROLE_CREATE,
        name: 'Agent Role MCP Create Role',
        description: 'Create an agent role and return normalized role payload',
        type: 'api_call' as const,
        category: 'System Intelligence',
        requiredPermissions: [{ id: 'agent_role_registry_write', name: 'Agent Role Registry Write', level: 'admin' }],
        tokenCost: 6,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            code: 'string',
            name: 'string',
            description: 'string',
            capabilities: 'string[]',
            tools: 'string[]',
            promptTemplate: 'string',
            status: 'string',
            tier: 'string',
          },
        },
      },
      {
        id: TOOL_ID__AGENT_ROLE_UPDATE,
        name: 'Agent Role MCP Update Role',
        description: 'Update an existing agent role by id',
        type: 'api_call' as const,
        category: 'System Intelligence',
        requiredPermissions: [{ id: 'agent_role_registry_write', name: 'Agent Role Registry Write', level: 'admin' }],
        tokenCost: 6,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            roleId: 'string',
            code: 'string',
            name: 'string',
            description: 'string',
            capabilities: 'string[]',
            tools: 'string[]',
            promptTemplate: 'string',
            status: 'string',
            tier: 'string',
          },
        },
      },
      {
        id: TOOL_ID__AGENT_ROLE_DELETE,
        name: 'Agent Role MCP Delete Role',
        description: 'Delete an agent role by id',
        type: 'api_call' as const,
        category: 'System Intelligence',
        requiredPermissions: [{ id: 'agent_role_registry_write', name: 'Agent Role Registry Write', level: 'admin' }],
        tokenCost: 5,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            roleId: 'string',
          },
        },
      },
      {
        id: TOOL_ID__AGENT_MODEL_LIST,
        name: 'Model MCP List Models',
        description: 'List models currently available in system registry',
        prompt: `当用户询问“系统里有哪些模型/当前有哪些模型/模型列表”时，请优先调用 ${TOOL_ID__AGENT_MODEL_LIST} 获取实时模型清单，再回答。`,
        type: 'data_analysis' as const,
        category: 'Model Management',
        requiredPermissions: [{ id: 'model_registry_read', name: 'Model Registry Read', level: 'basic' }],
        tokenCost: 3,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            provider: 'string',
            limit: 'number',
          },
        },
      },
      {
        id: TOOL_ID__AGENT_MODEL_ADD,
        name: 'Model MCP Add Model',
        description: 'Add a model into system model registry with deduplication',
        type: 'data_analysis' as const,
        category: 'Model Management',
        requiredPermissions: [{ id: 'model_registry_write', name: 'Model Registry Write', level: 'admin' }],
        tokenCost: 5,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            provider: 'string',
            model: 'string',
            name: 'string',
            id: 'string',
            maxTokens: 'number',
            temperature: 'number',
            topP: 'number',
          },
        },
      },
      {
        id: TOOL_ID__AGENT_MEMORY_SEARCH_MEMO,
        name: 'Memo MCP Search',
        description: 'Search agent memo memory with progressive loading summaries',
        prompt: `在处理任务时，优先调用 ${TOOL_ID__AGENT_MEMORY_SEARCH_MEMO} 检索相关历史备忘录。`,
        type: 'data_analysis' as const,
        category: 'Memory',
        authFree: true,
        requiredPermissions: [{ id: 'memo_read', name: 'Agent Memo Read', level: 'basic' }],
        tokenCost: 2,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            query: 'string',
            category: 'string',
            memoType: 'string',
            limit: 'number',
            detail: 'boolean',
          },
        },
      },
      {
        id: TOOL_ID__AGENT_MEMORY_APPEND_MEMO,
        name: 'Memo MCP Append',
        description: 'Append or create memo entries for long-term memory',
        prompt: `当形成关键结论或后续动作时，调用 ${TOOL_ID__AGENT_MEMORY_APPEND_MEMO} 追加到目标Agent备忘录。必须显式传 targetAgentId（或 agentId）写入目标对象；topic 必须 memoType=knowledge；achievement/criticism 必须 memoType=standard 且按追加模式写入，已有内容前先插入分割线“—”再追加新记录，禁止覆盖历史。`,
        type: 'data_analysis' as const,
        category: 'Memory',
        authFree: true,
        requiredPermissions: [{ id: 'memo_write', name: 'Agent Memo Write', level: 'basic' }],
        tokenCost: 3,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            title: 'string',
            content: 'string',
            category: 'string',
            memoType: 'string',
            memoKind: 'string',
            targetAgentId: 'string',
            memoId: 'string',
            taskId: 'string',
            topic: 'string',
            tags: 'string[]',
          },
        },
      },
      {
        id: TOOL_ID__AGENT_SKILL_LIST,
        name: 'Skill MCP List Skills',
        description: 'List system skills with optional title fuzzy search',
        type: 'data_analysis' as const,
        category: 'Skill',
        requiredPermissions: [{ id: 'skill_read', name: 'Skill Read', level: 'basic' }],
        tokenCost: 2,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            title: 'string',
            status: 'string',
            category: 'string',
            includeMetadata: 'boolean',
            limit: 'number',
            page: 'number',
          },
        },
      },
      {
        id: TOOL_ID__AGENT_SKILL_CREATE,
        name: 'Skill MCP Create Skill',
        description: 'Create a new skill in system skill library',
        type: 'api_call' as const,
        category: 'Skill',
        requiredPermissions: [{ id: 'skill_write', name: 'Skill Write', level: 'intermediate' }],
        tokenCost: 4,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            title: 'string',
            name: 'string',
            description: 'string',
            category: 'string',
            tags: 'string[]',
            sourceType: 'string',
            sourceUrl: 'string',
            provider: 'string',
            version: 'string',
            status: 'string',
            confidenceScore: 'number',
            metadata: 'object',
            content: 'string',
            contentType: 'string',
          },
        },
      },
      {
        id: TOOL_ID__EMPLYEE_LOGS,
        name: 'Human Operation Log MCP List',
        description: 'List operation logs for the human bound to the requesting exclusive assistant',
        type: 'data_analysis' as const,
        category: 'Audit',
        requiredPermissions: [{ id: 'human_operation_log_read', name: 'Human Operation Log Read', level: 'basic' }],
        tokenCost: 4,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            from: 'string',
            to: 'string',
            action: 'string',
            resourceKeyword: 'string',
            success: 'boolean',
            statusCode: 'number',
            page: 'number',
            pageSize: 'number',
          },
        },
      },
      {
        id: TOOL_ID__ORCHESTRATION_CREATE_PLAN,
        name: 'Orchestration Create Plan',
        description: 'Create orchestration plan from prompt in meeting workflow',
        type: 'api_call' as const,
        category: 'Orchestration',
        requiredPermissions: [{ id: 'orchestration_write', name: 'Orchestration Write', level: 'intermediate' }],
        tokenCost: 6,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            prompt: 'string',
            title: 'string',
            mode: 'string',
            plannerAgentId: 'string',
            autoRun: 'boolean',
            requirementId: 'string',
          },
        },
      },
      {
        id: TOOL_ID__ORCHESTRATION_UPDATE_PLAN,
        name: 'Orchestration Update Plan',
        description: 'Update orchestration plan in meeting workflow',
        type: 'api_call' as const,
        category: 'Orchestration',
        requiredPermissions: [{ id: 'orchestration_write', name: 'Orchestration Write', level: 'intermediate' }],
        tokenCost: 4,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            planId: 'string',
            title: 'string',
            prompt: 'string',
            mode: 'string',
            plannerAgentId: 'string',
            metadata: 'object',
          },
        },
      },
      {
        id: TOOL_ID__ORCHESTRATION_RUN_PLAN,
        name: 'Orchestration Run Plan',
        description: 'Run an orchestration plan in meeting workflow',
        type: 'api_call' as const,
        category: 'Orchestration',
        requiredPermissions: [{ id: 'orchestration_write', name: 'Orchestration Write', level: 'intermediate' }],
        tokenCost: 4,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            planId: 'string',
            continueOnFailure: 'boolean',
            confirm: 'boolean',
          },
        },
      },
      {
        id: TOOL_ID__ORCHESTRATION_GET_PLAN,
        name: 'Orchestration Get Plan',
        description: 'Get orchestration plan details',
        type: 'api_call' as const,
        category: 'Orchestration',
        requiredPermissions: [{ id: 'orchestration_read', name: 'Orchestration Read', level: 'basic' }],
        tokenCost: 3,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            planId: 'string',
          },
        },
      },
      {
        id: TOOL_ID__ORCHESTRATION_LIST_PLANS,
        name: 'Orchestration List Plans',
        description: 'List orchestration plans',
        type: 'api_call' as const,
        category: 'Orchestration',
        requiredPermissions: [{ id: 'orchestration_read', name: 'Orchestration Read', level: 'basic' }],
        tokenCost: 2,
        implementation: {
          type: 'built_in' as const,
          parameters: {},
        },
      },
      {
        id: TOOL_ID__ORCHESTRATION_INIT_PLAN,
        name: 'Orchestration Plan Initialize',
        description: 'Write structured initialize data to plan metadata',
        type: 'api_call' as const,
        category: 'Orchestration',
        requiredPermissions: [{ id: 'orchestration_write', name: 'Orchestration Write', level: 'intermediate' }],
        tokenCost: 3,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            type: 'object',
            required: ['planId', 'mode', 'data'],
            additionalProperties: false,
            properties: {
              planId: { type: 'string', description: '计划 ID' },
              mode: { type: 'string', description: '写入模式，当前支持 outline/taskContext' },
              data: { description: '写入内容：mode=outline 时传数组 [{step,title,taskType,recommendedAgent,phasePrompts}]，mode=taskContext 时传对象 {key:value}' },
            },
          },
        },
      },
      {
        id: TOOL_ID__ORCHESTRATION_SUBMIT_TASK,
        name: 'Orchestration Submit Task',
        description: 'Planner submits and creates next orchestration task',
        type: 'api_call' as const,
        category: 'Orchestration',
        terminal: true,
        requiredPermissions: [{ id: 'orchestration_write', name: 'Orchestration Write', level: 'intermediate' }],
        tokenCost: 3,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            type: 'object',
            required: ['planId', 'action', 'title', 'description'],
            additionalProperties: false,
            properties: {
              planId: { type: 'string', description: '计划 ID' },
              action: { type: 'string', enum: ['new', 'redesign'], description: 'new=新建任务, redesign=重设计失败任务' },
              title: { type: 'string', description: '任务标题' },
              description: { type: 'string', description: '任务描述' },
              priority: { type: 'string', enum: ['low', 'medium', 'high', 'urgent'], description: '任务优先级，默认 medium' },
              taskType: {
                type: 'string',
                enum: ['general', 'research', 'development.plan', 'development.exec', 'development.review'],
                description: '任务类型',
              },
              agentId: { type: 'string', description: '指定执行者 agent ID' },
              executorId: { type: 'string', description: '指定执行者 agent ID（兼容字段，等价于 agentId）' },
              requiredTools: { type: 'array', items: { type: 'string' }, description: '任务所需工具列表' },
              reasoning: { type: 'string', description: '规划依据' },
              redesignTaskId: { type: 'string', description: 'action=redesign 时必填，目标 taskId' },
              isGoalReached: { type: 'boolean', description: 'true 表示目标达成，不创建任务' },
            },
          },
        },
      },
      {
        id: TOOL_ID__ORCHESTRATION_SUBMIT_TASK_RUN_RESULT,
        name: 'Orchestration Report Task Run Result',
        description: 'Planner reports post-execution decision for current task',
        type: 'api_call' as const,
        category: 'Orchestration',
        terminal: true,
        requiredPermissions: [{ id: 'orchestration_write', name: 'Orchestration Write', level: 'intermediate' }],
        tokenCost: 2,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            type: 'object',
            required: ['planId', 'action', 'reason'],
            additionalProperties: false,
            properties: {
              planId: { type: 'string', description: '计划 ID' },
              action: { type: 'string', enum: ['generate_next', 'stop', 'redesign', 'retry'], description: '下一步动作' },
              reason: { type: 'string', description: '决策原因' },
              redesignTaskId: { type: 'string', description: 'action=redesign 时必填，目标 taskId' },
              nextTaskHints: { type: 'array', items: { type: 'string' }, description: '下一步提示信息' },
            },
          },
        },
      },
      {
        id: TOOL_ID__REQUIREMENT_LIST,
        name: 'Requirement List',
        description: 'List EI requirements with filters or board view',
        type: 'api_call' as const,
        category: 'Engineering Intelligence',
        requiredPermissions: [{ id: 'requirement_read', name: 'Requirement Read', level: 'basic' }],
        tokenCost: 3,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            view: 'string',
            status: 'string',
            assigneeAgentId: 'string',
            localProjectId: 'string',
            search: 'string',
            limit: 'number',
          },
        },
      },
      {
        id: TOOL_ID__REQUIREMENT_GET,
        name: 'Requirement Get',
        description: 'Get EI requirement details',
        type: 'api_call' as const,
        category: 'Engineering Intelligence',
        requiredPermissions: [{ id: 'requirement_read', name: 'Requirement Read', level: 'basic' }],
        tokenCost: 2,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            requirementId: 'string',
          },
        },
      },
      {
        id: TOOL_ID__REQUIREMENT_CREATE,
        name: 'Requirement Create',
        description: 'Create EI requirement',
        type: 'api_call' as const,
        category: 'Engineering Intelligence',
        requiredPermissions: [{ id: 'requirement_write', name: 'Requirement Write', level: 'intermediate' }],
        tokenCost: 5,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            title: 'string',
            description: 'string',
            priority: 'string',
            labels: 'string[]',
            createdById: 'string',
            createdByName: 'string',
            createdByType: 'string',
            localProjectId: 'string',
          },
        },
      },
      {
        id: TOOL_ID__REQUIREMENT_UPDATE_STATUS,
        name: 'Requirement Update Status',
        description: 'Update EI requirement status. Supports orchestration context fields (planId, taskType, executorAgentId, etc.) and assignee override (toAgentId/toAgentName). planId is auto-filled from collaboration context if not provided.',
        prompt:
          '会议分配场景请先更新 requirement 状态（建议 assigned 或 in_progress）再发送通知；若用户已明确同意执行，不要再二次确认文案。编排场景请传入 toAgentId/toAgentName 设置需求负责人，planId 会自动从编排上下文注入。',
        type: 'api_call' as const,
        category: 'Engineering Intelligence',
        requiredPermissions: [{ id: 'requirement_write', name: 'Requirement Write', level: 'intermediate' }],
        tokenCost: 3,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            requirementId: 'string',
            status: 'string',
            changedById: 'string',
            changedByName: 'string',
            changedByType: 'string',
            note: 'string',
            toAgentId: 'string',
            toAgentName: 'string',
            planId: 'string',
            taskType: 'string',
            executorAgentId: 'string',
            executorAgentName: 'string',
            taskTitle: 'string',
          },
        },
      },
      {
        id: TOOL_ID__REQUIREMENT_UPDATE,
        name: 'Requirement Update',
        description: 'Update requirement by action (assign/comment/update_status)',
        prompt:
          '会议分配场景执行 requirement.update(action=assign) 后，必须补充结构化三段式回执：动作1（已分配：requirementId/执行人/状态）+ 动作2（已通知：消息摘要）+ 下一步（检查时间点）。用户明确同意后直接执行，不重复确认语气。',
        type: 'api_call' as const,
        category: 'Engineering Intelligence',
        requiredPermissions: [{ id: 'requirement_write', name: 'Requirement Write', level: 'intermediate' }],
        tokenCost: 3,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            action: 'string',
            requirementId: 'string',
            status: 'string',
            changedById: 'string',
            changedByName: 'string',
            changedByType: 'string',
            note: 'string',
            toAgentId: 'string',
            toAgentName: 'string',
            assignedById: 'string',
            assignedByName: 'string',
            reason: 'string',
            content: 'string',
            authorId: 'string',
            authorName: 'string',
            authorType: 'string',
          },
        },
      },
      {
        id: TOOL_ID__REQUIREMENT_SYNC_GITHUB,
        name: 'Requirement Sync Github',
        description: 'Sync EI requirement to GitHub issue',
        type: 'api_call' as const,
        category: 'Engineering Intelligence',
        requiredPermissions: [{ id: 'requirement_write', name: 'Requirement Write', level: 'intermediate' }],
        tokenCost: 4,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            requirementId: 'string',
            owner: 'string',
            repo: 'string',
            labels: 'string[]',
          },
        },
      },
      {
        id: TOOL_ID__MEETING_LIST,
        name: 'Meeting MCP List',
        description: 'List current meetings (without message details)',
        type: 'data_analysis' as const,
        category: 'Meeting',
        requiredPermissions: [{ id: 'meeting_read', name: 'Meeting Read', level: 'basic' }],
        tokenCost: 2,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            status: 'string',
            limit: 'number',
          },
        },
      },
      {
        id: TOOL_ID__MEETING_GET_DETAIL,
        name: 'Meeting MCP Get Detail',
        description: 'Get meeting detail with messages',
        type: 'api_call' as const,
        category: 'Meeting',
        requiredPermissions: [{ id: 'meeting_read', name: 'Meeting Read', level: 'basic' }],
        tokenCost: 3,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            meetingId: 'string',
          },
        },
      },
      {
        id: TOOL_ID__MEETING_SEND_MESSAGE,
        name: 'Meeting MCP Send Message',
        description: 'Send a message to a specific meeting',
        type: 'api_call' as const,
        category: 'Meeting',
        requiredPermissions: [{ id: 'meeting_write', name: 'Meeting Write', level: 'basic' }],
        tokenCost: 3,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            meetingId: 'string',
            content: 'string',
            type: 'string',
          },
        },
      },
      {
        id: TOOL_ID__MEETING_UPDATE_STATUS,
        name: 'Meeting MCP Update Status',
        description: 'Update meeting status (start/end/pause/resume)',
        type: 'api_call' as const,
        category: 'Meeting',
        requiredPermissions: [{ id: 'meeting_write', name: 'Meeting Write', level: 'intermediate' }],
        tokenCost: 4,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            meetingId: 'string',
            action: 'string',
          },
        },
      },
      {
        id: TOOL_ID__MEETING_SAVE_SUMMARY,
        name: 'Meeting MCP Save Summary',
        description: 'Save generated meeting summary content',
        type: 'api_call' as const,
        category: 'Meeting',
        requiredPermissions: [{ id: 'meeting_write', name: 'Meeting Write', level: 'intermediate' }],
        tokenCost: 5,
        implementation: {
          type: 'built_in' as const,
          parameters: {
            meetingId: 'string',
            summary: 'string',
            actionItems: 'string[]',
            decisions: 'string[]',
            overwrite: 'boolean',
          },
        },
      },
    ];

export const IMPLEMENTED_TOOL_IDS = [
  ...BUILTIN_TOOLS.map((tool) => tool.id),
];

/**
 * 终态工具 ID 集合：这些工具成功执行后，agent executor 立即终止 tool-calling 循环。
 * 从 BUILTIN_TOOLS 静态过滤，避免运行时 DB 查询。
 */
export const TERMINAL_TOOL_IDS: ReadonlySet<string> = new Set(
  BUILTIN_TOOLS.filter((t) => (t as any).terminal === true).map((t) => t.id),
);

/**
 * 免授权工具 ID 集合：所有 Agent 默认携带，无需 MCP Profile 或角色授权。
 * 从 BUILTIN_TOOLS 静态过滤，避免运行时 DB 查询。
 */
export const AUTH_FREE_TOOL_IDS: ReadonlySet<string> = new Set(
  BUILTIN_TOOLS.filter((t) => (t as any).authFree === true).map((t) => t.id),
);
